FROM rust:1-trixie as builder

WORKDIR /app
COPY . /app
RUN --mount=type=cache,target=/usr/local/cargo/registry cargo build --release

# ---

FROM debian:trixie

COPY --from=builder /app/target/release/hackku26 /usr/local/bin/hackku26
CMD ["hackku26"]
